export {
  init,
  ensureCellCapacity,
  ensureFormulaCapacity,
  ensureConstantCapacity,
  ensureRangeCapacity,
  ensureMemberCapacity,
  uploadPrograms,
  uploadConstants,
  uploadRangeMembers,
  uploadRangeShapes,
  uploadVolatileNowSerial,
  uploadVolatileRandomValues,
  uploadStringLengths,
  uploadStrings,
  writeCells,
  evalBatch,
  getOutputStringLengthsPtr,
  getOutputStringOffsetsPtr,
  getOutputStringDataPtr,
  getOutputStringCount,
  getOutputStringDataLength,
  getSpillResultRowsPtr,
  getSpillResultColsPtr,
  getSpillResultOffsetsPtr,
  getSpillResultLengthsPtr,
  getSpillResultTagsPtr,
  getSpillResultNumbersPtr,
  getSpillResultValueCount,
} from './vm'

export { evalDirectScalarStoreTargetBatch, evalDirectScalarValueBatch } from './direct-scalar-batch'
export { evalDenseDirectScalarRowChainStoreTargetBatch } from './direct-scalar-row-chain-batch'
export { evalAnchoredPrefixAggregateBatch, evalDenseNumericRowAggregateBatch } from './direct-aggregate-batch'
export { evalDirectCriteriaMatchedAggregateBatch, evalDirectCriteriaPredicateAggregateBatch } from './direct-criteria-aggregate-batch'
export { evalUniformNumericLookupBatch } from './direct-lookup-batch'

export {
  getTagsPtr,
  getNumbersPtr,
  getStringIdsPtr,
  getErrorsPtr,
  getProgramOffsetsPtr,
  getProgramLengthsPtr,
  getConstantOffsetsPtr,
  getConstantLengthsPtr,
  getConstantArenaPtr,
  getRangeOffsetsPtr,
  getRangeLengthsPtr,
  getRangeMembersPtr,
  getCellCapacity,
  getFormulaCapacity,
  getConstantCapacity,
  getRangeCapacity,
  getMemberCapacity,
} from './vm-accessors'

export {
  materializePivotTable,
  getPivotResultTagsPtr,
  getPivotResultNumbersPtr,
  getPivotResultStringIdsPtr,
  getPivotResultErrorsPtr,
  pivotResultRows,
  pivotResultCols,
} from './pivot'

export {
  addWorksheetImportFormulaOnlyCell,
  addWorksheetImportFormulaRecord,
  addWorksheetImportNumberCellFromScratch,
  addWorksheetImportNumberCell,
  addWorksheetImportSharedStringCell,
  addWorksheetImportStyle,
  getWorksheetImportCellCount,
  getWorksheetImportColumnsPtr,
  getWorksheetImportFormulaCellIndexesPtr,
  getWorksheetImportFormulaColumnsPtr,
  getWorksheetImportFormulaCount,
  getWorksheetImportFormulaRowsPtr,
  getWorksheetImportFormulaSharedIndexesPtr,
  getWorksheetImportFormulaTypeCodesPtr,
  getWorksheetImportNumbersPtr,
  getWorksheetImportRowsPtr,
  getWorksheetImportSharedStringIdsPtr,
  getWorksheetImportStyleColumnsPtr,
  getWorksheetImportStyleCount,
  getWorksheetImportStyleIdsPtr,
  getWorksheetImportStyleRowsPtr,
  getWorksheetImportValueKindsPtr,
  prepareWorksheetImportScratch,
  readWorksheetImportNonNegativeIntegerFromScratch,
  releaseWorksheetImportStorage,
  resetWorksheetImportStorage,
  worksheetImportNoSharedFormulaIndex,
  worksheetImportValueKindFormulaOnly,
  worksheetImportValueKindNumber,
  worksheetImportValueKindSharedString,
} from './worksheet-import-storage'
