export const TEXT_FIXTURE_METADATA = {
  source: 'excel-web-like text builtin tranche',
  version: 2,
  builtins: [
    'LEN',
    'LENB',
    'CONCAT',
    'LEFT',
    'LEFTB',
    'RIGHT',
    'RIGHTB',
    'MID',
    'MIDB',
    'CLEAN',
    'TRIM',
    'UPPER',
    'LOWER',
    'FIND',
    'FINDB',
    'SEARCH',
    'SEARCHB',
    'REPLACE',
    'REPLACEB',
    'REPT',
    'ASC',
    'JIS',
    'DBCS',
    'VALUE',
    'TEXTBEFORE',
    'TEXTAFTER',
    'TEXTJOIN',
    'TEXTSPLIT',
  ] as const,
} as const
