import { agentNotAFitBoundaries, mcpPromptNames } from './agent-discovery-constants.ts'
import { buildEvaluatorDoors, buildProofContract, compactProofContractJsonArrays } from './agent-discovery-evaluator-doors.ts'

export type BuildAgentJsonManifestInput = {
  readonly siteRoot: string
  readonly repositoryUrl: string
  readonly skillDiscoveryRoot: string
  readonly skillManifestUrl: string
  readonly skillName: string
  readonly workpaperPackageSpec: string
  readonly remoteMcpEndpoint: string
  readonly remoteMcpAliasEndpoint: string
  readonly remoteMcpServerCard: string
  readonly mcpbReleaseAssetUrl: string
  readonly mcpbReleaseChecksumUrl: string
}

export function buildAgentJsonManifest(input: BuildAgentJsonManifestInput): string {
  const {
    mcpbReleaseAssetUrl,
    mcpbReleaseChecksumUrl,
    remoteMcpAliasEndpoint,
    remoteMcpEndpoint,
    remoteMcpServerCard,
    repositoryUrl,
    siteRoot,
    skillDiscoveryRoot,
    skillManifestUrl,
    skillName,
    workpaperPackageSpec,
  } = input
  const json = JSON.stringify(
    {
      schema_version: 'agent-json-0.1.0',
      name: 'bilig',
      title: 'Bilig WorkPaper formula runtime',
      description:
        'Formula WorkPaper runtime for Node.js services and agent tools: edit cells, recalculate, verify readback, and persist JSON without spreadsheet UI automation.',
      url: `${siteRoot}/`,
      repository: repositoryUrl,
      license: 'MIT',
      contact: `${repositoryUrl}/discussions/new?category=general`,
      llms_txt: `${siteRoot}/llms.txt`,
      llms_full: `${siteRoot}/llms-full.txt`,
      llms_install: `${siteRoot}/llms-install.html`,
      llms_install_source: `${repositoryUrl}/blob/main/llms-install.md`,
      well_known_llms_txt: `${siteRoot}/.well-known/llms.txt`,
      well_known_llms_full: `${siteRoot}/.well-known/llms-full.txt`,
      agent_start: `${siteRoot}/agent-start.txt`,
      well_known_agent_start: `${siteRoot}/.well-known/agent-start.txt`,
      skill_file: skillManifestUrl,
      agent_instructions: `${siteRoot}/AGENTS.md`,
      adoption_kit: `${siteRoot}/agent-adoption-kit.html`,
      skills: [
        {
          name: skillName,
          url: skillManifestUrl,
          index_url: `${siteRoot}/.well-known/agent-skills/index.json`,
          description:
            'Use @bilig/workpaper WorkPaper state, MCP tools, and formula-clinic reports instead of spreadsheet UI automation when an agent needs formula readback.',
        },
      ],
      evaluator_doors: buildEvaluatorDoors({ repositoryUrl, siteRoot, workpaperPackageSpec }),
      mcp: {
        server_name: 'io.github.proompteng/bilig-workpaper',
        server_card: `${siteRoot}/.well-known/mcp/server-card.json`,
        remote_server_card: remoteMcpServerCard,
        manifest: `${siteRoot}/.well-known/mcp.json`,
        registry_search: 'https://registry.modelcontextprotocol.io/v0.1/servers?search=io.github.proompteng%2Fbilig-workpaper',
        remote_endpoint: remoteMcpEndpoint,
        remote_alias_endpoint: remoteMcpAliasEndpoint,
        remote_transport: {
          type: 'streamable-http',
          protocol_version: '2025-11-25',
          stateless: true,
          authentication_required: false,
        },
        command: 'npm',
        args: [
          'exec',
          '--package',
          workpaperPackageSpec,
          '--',
          'bilig-workpaper-mcp',
          '--workpaper',
          './pricing.workpaper.json',
          '--init-demo-workpaper',
          '--writable',
        ],
        tools: [
          'list_sheets',
          'read_range',
          'read_cell',
          'set_cell_contents',
          'set_cell_contents_and_readback',
          'get_cell_display_value',
          'export_workpaper_document',
          'validate_formula',
        ],
        resources: [
          'bilig://workpaper/manifest',
          'bilig://workpaper/agent-handoff',
          'bilig://workpaper/sheets',
          'bilig://workpaper/current-document',
        ],
        prompts: ['edit_and_verify_workpaper', 'debug_workpaper_formula'],
      },
      capabilities: [
        {
          name: 'agent-start',
          type: 'plain-text-entrypoint',
          url: `${siteRoot}/agent-start.txt`,
          well_known_url: `${siteRoot}/.well-known/agent-start.txt`,
          decision_command: `npm exec --yes --package ${workpaperPackageSpec} -- bilig-agent-start --json`,
          challenge_command: `npm exec --yes --package ${workpaperPackageSpec} -- bilig-evaluate --door agent-mcp --json`,
        },
        {
          name: 'agent-adoption-kit',
          type: 'docs-entrypoint',
          docs: `${siteRoot}/agent-adoption-kit.html`,
          skill_install: `npx --yes skills@latest add ${skillDiscoveryRoot} --list`,
          challenge_command: `npm exec --yes --package ${workpaperPackageSpec} -- bilig-evaluate --door agent-mcp --json`,
        },
        {
          name: 'workbook-agent-intent-api',
          type: 'npm-library',
          package: '@bilig/workbook',
          runtime: 'Node.js >=22',
          install: 'npm install @bilig/workbook',
          docs: `${siteRoot}/workbook-agent-intent-api.html`,
          source: `${repositoryUrl}/tree/main/examples/workbook-agent-model`,
        },
        {
          name: 'workpaper-formula-runtime',
          type: 'npm-library',
          package: '@bilig/workpaper',
          runtime: 'Node.js >=22',
          install: 'npm install @bilig/workpaper',
          docs: `${siteRoot}/try-bilig-headless-in-node.html`,
        },
        {
          name: 'file-backed-workpaper-mcp',
          type: 'mcp-stdio-server',
          docs: `${siteRoot}/mcp-workpaper-tool-server.html`,
          server_card: `${siteRoot}/.well-known/mcp/server-card.json`,
          challenge_command: `npm exec --package ${workpaperPackageSpec} -- bilig-mcp-challenge`,
        },
        {
          name: 'repo-local-mcp-configs',
          type: 'project-mcp-configs',
          claude_code: `${repositoryUrl}/blob/main/.mcp.json`,
          cursor: `${repositoryUrl}/blob/main/.cursor/mcp.json`,
          vscode: `${repositoryUrl}/blob/main/.vscode/mcp.json`,
          reusable: `${repositoryUrl}/blob/main/mcp/bilig-workpaper.mcp.json`,
          docs: `${siteRoot}/mcp-client-setup.html`,
          workpaper_state_path: './.bilig/pricing.workpaper.json',
        },
        {
          name: 'gemini-cli-workpaper-extension',
          type: 'gemini-cli-extension',
          install: repositoryUrl,
          install_command: `gemini extensions install ${repositoryUrl} --ref main`,
          manifest: `${repositoryUrl}/blob/main/gemini-extension.json`,
          context: `${repositoryUrl}/blob/main/gemini-workpaper-context.md`,
          docs: `${siteRoot}/gemini-cli-workpaper-extension.html`,
        },
        {
          name: 'claude-desktop-mcpb',
          type: 'mcpb-desktop-extension',
          download_url: mcpbReleaseAssetUrl,
          checksum_url: mcpbReleaseChecksumUrl,
          docs: `${siteRoot}/claude-desktop-mcpb-workpaper.html`,
        },
        {
          name: 'remote-workpaper-mcp-demo',
          type: 'mcp-streamable-http-server',
          endpoint: remoteMcpEndpoint,
          alias_endpoint: remoteMcpAliasEndpoint,
          server_card: remoteMcpServerCard,
          protocol_version: '2025-11-25',
          authentication_required: false,
          docs: `${siteRoot}/mcp-workpaper-tool-server.html#remote-stateless-endpoint`,
        },
        {
          name: 'openai-agents-sdk-hosted-workpaper-mcp',
          type: 'typescript-agent-mcp-smoke-test',
          framework: 'OpenAI Agents SDK',
          transport: 'streamable-http',
          endpoint: remoteMcpEndpoint,
          command: 'pnpm --dir examples/headless-workpaper run agent:openai-agents-sdk-hosted-mcp',
          docs: `${siteRoot}/openai-agents-sdk-workpaper-tool.html`,
          source: `${repositoryUrl}/blob/main/examples/headless-workpaper/openai-agents-sdk-hosted-mcp-smoke.ts`,
        },
        {
          name: 'openai-responses-workpaper-tool-calls',
          type: 'typescript-function-calling-dispatcher',
          framework: 'OpenAI Responses API',
          api_shape: 'function_call -> function_call_output',
          command: 'pnpm --dir examples/headless-workpaper run agent:openai-responses',
          docs: `${siteRoot}/openai-responses-workpaper-tool-call.html`,
          source: `${repositoryUrl}/blob/main/examples/headless-workpaper/openai-responses-tool-wrapper.ts`,
        },
        {
          name: 'browser-use-workpaper-formula-tool',
          type: 'python-browser-agent-tool-guide',
          framework: 'Browser Use',
          command: `npm exec --yes --package ${workpaperPackageSpec} -- bilig-evaluate --door agent-mcp --json`,
          docs: `${siteRoot}/browser-use-workpaper-formula-tool.html`,
          source: `${repositoryUrl}/blob/main/docs/browser-use-workpaper-formula-tool.md`,
          upstream_pr: 'https://github.com/browser-use/browser-use/pull/4909',
        },
        {
          name: 'chatgpt-apps-workpaper-mcp',
          type: 'chatgpt-developer-mode-remote-mcp-app',
          framework: 'ChatGPT Apps',
          transport: 'streamable-http',
          endpoint: remoteMcpEndpoint,
          authentication_required: false,
          docs: `${siteRoot}/chatgpt-apps-workpaper-mcp.html`,
          server_card: remoteMcpServerCard,
          proof_command: `npm exec --yes --package ${workpaperPackageSpec} -- bilig-evaluate --door agent-mcp --json`,
        },
        {
          name: 'fastmcp-workpaper-client',
          type: 'python-mcp-client-smoke-test',
          endpoint: remoteMcpEndpoint,
          client: 'FastMCP',
          docs: `${siteRoot}/fastmcp-workpaper-client.html`,
          source: `${repositoryUrl}/tree/main/examples/fastmcp-workpaper-client`,
        },
        {
          name: 'agno-workpaper-mcp',
          type: 'python-agent-mcp-smoke-test',
          framework: 'Agno',
          command:
            'uv run --python 3.12 --with agno --with mcp --with openai python examples/agno-workpaper-mcp/agno_workpaper_mcp.py --output .tmp/agno-workpaper-proof.json',
          docs: `${siteRoot}/agno-workpaper-mcp.html`,
          source: `${repositoryUrl}/tree/main/examples/agno-workpaper-mcp`,
        },
        {
          name: 'pydantic-ai-workpaper-mcp',
          type: 'python-agent-mcp-smoke-test',
          framework: 'Pydantic AI',
          command:
            'uv run --python 3.12 --with pydantic-ai --with mcp --with fastmcp python examples/pydantic-ai-workpaper-mcp/pydantic_ai_workpaper_mcp.py --output .tmp/pydantic-ai-workpaper-proof.json',
          docs: `${siteRoot}/pydantic-ai-workpaper-mcp.html`,
          source: `${repositoryUrl}/tree/main/examples/pydantic-ai-workpaper-mcp`,
        },
        {
          name: 'google-adk-workpaper-mcp',
          type: 'python-agent-mcp-smoke-test',
          framework: 'Google Agent Development Kit',
          command:
            'uv run --python 3.12 --with google-adk --with mcp python examples/google-adk-workpaper-mcp/google_adk_workpaper_mcp.py --output .tmp/google-adk-workpaper-proof.json',
          docs: `${siteRoot}/google-adk-workpaper-mcp.html`,
          source: `${repositoryUrl}/tree/main/examples/google-adk-workpaper-mcp`,
        },
        {
          name: 'semantic-kernel-workpaper-mcp',
          type: 'python-agent-mcp-smoke-test',
          framework: 'Microsoft Semantic Kernel',
          command:
            "uv run --python 3.12 --with 'semantic-kernel[mcp]' python examples/semantic-kernel-workpaper-mcp/semantic_kernel_workpaper_mcp.py --output .tmp/semantic-kernel-workpaper-proof.json",
          docs: `${siteRoot}/semantic-kernel-workpaper-mcp.html`,
          source: `${repositoryUrl}/tree/main/examples/semantic-kernel-workpaper-mcp`,
        },
        {
          name: 'smolagents-workpaper-tool',
          type: 'python-agent-tool-smoke-test',
          framework: 'smolagents',
          command: 'uv run --python 3.12 --with smolagents python examples/smolagents-workpaper-tool/smolagents_workpaper_tool.py',
          docs: `${siteRoot}/smolagents-workpaper-tool.html`,
          source: `${repositoryUrl}/tree/main/examples/smolagents-workpaper-tool`,
        },
        {
          name: 'huggingface-workpaper-space-template',
          type: 'gradio-mcp-space-template',
          framework: 'Hugging Face Spaces',
          command:
            "cd examples/huggingface-workpaper-space && npm install --omit=dev --package-lock=false && uv run --python 3.12 --with 'gradio[mcp]>=6.0,<7' python app.py --check",
          docs: `${siteRoot}/huggingface-workpaper-space.html`,
          source: `${repositoryUrl}/tree/main/examples/huggingface-workpaper-space`,
        },
        {
          name: 'inngest-workpaper-step',
          type: 'durable-workflow-step-smoke-test',
          framework: 'Inngest',
          command: 'cd examples/inngest-workpaper-step && pnpm install --ignore-workspace --lockfile=false && pnpm run smoke',
          docs: `${siteRoot}/inngest-workpaper-step.html`,
          source: `${repositoryUrl}/tree/main/examples/inngest-workpaper-step`,
        },
        {
          name: 'airbyte-workpaper-validation',
          type: 'post-sync-validation-smoke-test',
          framework: 'Airbyte',
          command: 'cd examples/airbyte-workpaper-validation && pnpm install --ignore-workspace --lockfile=false && pnpm run smoke',
          docs: `${siteRoot}/airbyte-workpaper-validation.html`,
          source: `${repositoryUrl}/tree/main/examples/airbyte-workpaper-validation`,
        },
        {
          name: 'meltano-workpaper-utility',
          type: 'elt-utility-smoke-test',
          framework: 'Meltano',
          command: 'cd examples/meltano-workpaper-utility && pnpm install --ignore-workspace --lockfile=false && pnpm run smoke',
          docs: `${siteRoot}/meltano-workpaper-utility.html`,
          source: `${repositoryUrl}/tree/main/examples/meltano-workpaper-utility`,
        },
        {
          name: 'formula-clinic',
          type: 'local-cli',
          command: `npm exec --package ${workpaperPackageSpec} -- bilig-formula-clinic ./reduced.xlsx --cells "Summary!B7,Inputs!B2"`,
          docs: `${siteRoot}/formula-bug-clinic.html`,
        },
      ],
      proof_contract: buildProofContract(),
      verification_contract: [
        'read the relevant range before editing',
        'write the target input or formula cell',
        'read the dependent calculated output after recalculation',
        'export or serialize the WorkPaper document',
        'restore or reimport when a file boundary matters',
        'return editedCell, before, after, afterRestore, persistedDocumentBytes, verified, and limitations',
      ],
      boundaries: {
        good_fit: [
          'pricing, quote approval, budget, payout, import-validation, and forecast logic',
          'agent tools that need deterministic cell addresses and formula readback',
          'service-owned workbook state that can persist as JSON',
        ],
        not_a_fit: agentNotAFitBoundaries,
      },
      public_entrypoints: [
        `${siteRoot}/`,
        `${siteRoot}/llms.txt`,
        `${siteRoot}/llms-full.txt`,
        `${siteRoot}/llms-install.html`,
        `${repositoryUrl}/blob/main/llms-install.md`,
        `${siteRoot}/.well-known/llms.txt`,
        `${siteRoot}/.well-known/llms-full.txt`,
        `${siteRoot}/agent-start.txt`,
        `${siteRoot}/.well-known/agent-start.txt`,
        `${siteRoot}/why-use-bilig.html`,
        `${siteRoot}/eval-xlsx-cache-doctor.html`,
        `${siteRoot}/eval-xlsx-recalc.html`,
        `${siteRoot}/xlsx-cache-doctor-github-action.html`,
        `${siteRoot}/agent-adoption-kit.html`,
        `${siteRoot}/headless-workpaper-agent-handbook.html`,
        `${repositoryUrl}/blob/main/.mcp.json`,
        `${repositoryUrl}/blob/main/.cursor/mcp.json`,
        `${repositoryUrl}/blob/main/mcp/bilig-workpaper.mcp.json`,
        `${siteRoot}/agent-workbook-challenge.html`,
        `${siteRoot}/mcp-workpaper-tool-server.html`,
        `${siteRoot}/open-webui-workpaper-mcp.html`,
        `${siteRoot}/open-multi-agent-workpaper-mcp.html`,
        `${siteRoot}/lobehub-workpaper-mcp.html`,
        `${siteRoot}/anythingllm-workpaper-mcp.html`,
        `${siteRoot}/sim-workpaper-mcp.html`,
        `${siteRoot}/fastmcp-workpaper-client.html`,
        `${siteRoot}/agno-workpaper-mcp.html`,
        `${siteRoot}/pydantic-ai-workpaper-mcp.html`,
        `${siteRoot}/google-adk-workpaper-mcp.html`,
        `${siteRoot}/smolagents-workpaper-tool.html`,
        `${siteRoot}/huggingface-workpaper-space.html`,
        remoteMcpEndpoint,
        remoteMcpServerCard,
        `${siteRoot}/agent-workpaper-tool-calling-recipe.html`,
        `${siteRoot}/agent-framework-workbook-tools.html`,
        `${siteRoot}/workbook-agent-intent-api.html`,
        `${siteRoot}/openai-agents-sdk-workpaper-tool.html`,
        `${siteRoot}/openai-responses-workpaper-tool-call.html`,
        `${siteRoot}/browser-use-workpaper-formula-tool.html`,
        `${siteRoot}/chatgpt-apps-workpaper-mcp.html`,
        `${siteRoot}/langgraph-workpaper-toolnode-spreadsheet.html`,
        `${siteRoot}/llamaindex-workpaper-spreadsheet-tool.html`,
        `${siteRoot}/crewai-workpaper-spreadsheet-tool.html`,
        `${siteRoot}/cloudflare-agents-workpaper-spreadsheet-tool.html`,
        `${siteRoot}/semantic-kernel-workpaper-mcp.html`,
        `${siteRoot}/gemini-cli-workpaper-extension.html`,
        `${siteRoot}/node-framework-workpaper-adapters.html`,
        `${siteRoot}/n8n-workpaper-formula-readback.html`,
        `${siteRoot}/dify-workpaper-formula-readback.html`,
        `${siteRoot}/flowise-workpaper-formula-readback.html`,
        `${siteRoot}/pipedream-workpaper-formula-readback.html`,
        `${siteRoot}/triggerdev-workpaper-task.html`,
        `${siteRoot}/inngest-workpaper-step.html`,
        `${siteRoot}/airbyte-workpaper-validation.html`,
        `${siteRoot}/meltano-workpaper-utility.html`,
        `${siteRoot}/temporal-workpaper-activity.html`,
        `${siteRoot}/airflow-workpaper-dag.html`,
        `${siteRoot}/dagster-workpaper-asset.html`,
        `${siteRoot}/kestra-workpaper-flow.html`,
        `${siteRoot}/prefect-workpaper-flow.html`,
        `${siteRoot}/npm-provenance-package-trust.html`,
      ],
    },
    null,
    2,
  )
  const compactPersistedBytesAlias = compactProofContractJsonArrays(json, compactStringArrayProperty)
  const compactPrompts = compactStringArrayProperty(compactPersistedBytesAlias, 'prompts', mcpPromptNames, '    ')
  return `${compactStringArrayProperty(compactPrompts, 'not_a_fit', agentNotAFitBoundaries, '    ')}\n`
}

function compactStringArrayProperty(json: string, propertyName: string, values: readonly string[], indent: string): string {
  const expanded = `${indent}"${propertyName}": [\n${values.map((value) => `${indent}  ${JSON.stringify(value)}`).join(',\n')}\n${indent}]`
  const compact = `${indent}"${propertyName}": [${values.map((value) => JSON.stringify(value)).join(', ')}]`
  return json.replace(expanded, compact)
}
