export const agentFrameworkLlmsRequiredLinks = [
  'https://proompteng.github.io/bilig/mastra-workpaper-spreadsheet-tool.html',
  'https://proompteng.github.io/bilig/llamaindex-workpaper-spreadsheet-tool.html',
  'https://proompteng.github.io/bilig/langgraph-workpaper-toolnode-spreadsheet.html',
  'https://proompteng.github.io/bilig/open-multi-agent-workpaper-mcp.html',
  'https://proompteng.github.io/bilig/agno-workpaper-mcp.html',
  'https://proompteng.github.io/bilig/pydantic-ai-workpaper-mcp.html',
  'https://proompteng.github.io/bilig/google-adk-workpaper-mcp.html',
  'https://proompteng.github.io/bilig/microsoft-agent-framework-workpaper-mcp.html',
  'https://proompteng.github.io/bilig/openhands-workpaper-mcp.html',
  'https://proompteng.github.io/bilig/trae-workpaper-mcp.html',
  'https://proompteng.github.io/bilig/qodo-workpaper-mcp.html',
  'https://proompteng.github.io/bilig/opencode-workpaper-mcp.html',
  'https://proompteng.github.io/bilig/goose-workpaper-mcp.html',
  'https://proompteng.github.io/bilig/copilotkit-workpaper-spreadsheet-action.html',
  'https://proompteng.github.io/bilig/cloudflare-agents-workpaper-spreadsheet-tool.html',
  'https://proompteng.github.io/bilig/crewai-workpaper-spreadsheet-tool.html',
  'https://proompteng.github.io/bilig/semantic-kernel-workpaper-mcp.html',
  'https://proompteng.github.io/bilig/browser-use-workpaper-formula-tool.html',
] as const

export const agentFrameworkDocRequirements = [
  {
    path: 'docs/agent-adoption-kit.md',
    includes: [
      'Choose Bilig instead of Excel or Sheets UI automation when',
      'formula readback after writes through `set_cell_contents_and_readback`',
      'persisted WorkPaper JSON',
      'compact proof object with `verified: true`',
      'npm exec --yes --package @bilig/workpaper@latest -- bilig-evaluate --door agent-mcp --json',
      'browser-use-workpaper-formula-tool.md',
      'headless-workpaper-agent-handbook.md',
      'agent-framework-workbook-tools.md',
    ],
  },
  {
    path: 'docs/mastra-workpaper-spreadsheet-tool.md',
    includes: [
      'Mastra WorkPaper spreadsheet tool',
      '@bilig/workpaper',
      '@mastra/core',
      'createTool',
      'pnpm --dir examples/mastra-workpaper-tool run smoke',
      'examples/mastra-workpaper-tool/src/mastra-workpaper-tool.ts',
      'pnpm --dir examples/headless-workpaper run agent:framework-adapters',
    ],
  },
  {
    path: 'docs/llamaindex-workpaper-spreadsheet-tool.md',
    includes: [
      'LlamaIndex.TS WorkPaper spreadsheet tool',
      '@bilig/workpaper',
      'tool(fn, { parameters })',
      'pnpm --dir examples/headless-workpaper run agent:framework-adapters',
    ],
  },
  {
    path: 'docs/langgraph-workpaper-toolnode-spreadsheet.md',
    includes: [
      'LangGraph.js WorkPaper ToolNode spreadsheet tool',
      '@langchain/langgraph',
      '@langchain/mcp-adapters',
      'new ToolNode(tools)',
      'examples/langgraph-workpaper-tool-state',
      'examples/langchain-mcp-workpaper-toolnode',
      'pnpm run smoke',
    ],
  },
  {
    path: 'docs/open-multi-agent-workpaper-mcp.md',
    includes: [
      'Open Multi-Agent WorkPaper MCP example',
      'connectMCPTools()',
      'was merged here',
      'bilig-evaluate --door agent-mcp --json',
      '@bilig/workpaper@latest',
      '60000 -> 96000',
      'verified',
    ],
  },
  {
    path: 'docs/agno-workpaper-mcp.md',
    includes: [
      'Agno WorkPaper MCP tools',
      'MCPTools',
      'examples/agno-workpaper-mcp',
      '@bilig/workpaper@latest',
      'set_cell_contents_and_readback',
      '60000',
      '96000',
      'restoredReadbackMatchesAfter',
    ],
  },
  {
    path: 'docs/pydantic-ai-workpaper-mcp.md',
    includes: [
      'Pydantic AI WorkPaper MCP tools',
      'MCPToolset',
      'StdioTransport',
      'examples/pydantic-ai-workpaper-mcp',
      '@bilig/workpaper@latest',
      'set_cell_contents_and_readback',
      'WorkPaperProof',
      '60000',
      '96000',
    ],
  },
  {
    path: 'docs/google-adk-workpaper-mcp.md',
    includes: [
      'Google ADK WorkPaper MCP tools',
      'https://adk.dev/tools-custom/mcp-tools/',
      'https://adk.dev/integrations/',
      'examples/google-adk-workpaper-mcp',
      '@bilig/workpaper@latest',
      'McpToolset',
      'StdioConnectionParams',
      'StdioServerParameters',
      'tool_filter',
      'set_cell_contents_and_readback',
      '60000',
      '96000',
      'verified: true',
      'No upstream Google ADK PR or issue was opened',
    ],
  },
  {
    path: 'docs/microsoft-agent-framework-workpaper-mcp.md',
    includes: [
      'Microsoft Agent Framework WorkPaper MCP Tools',
      'https://learn.microsoft.com/en-us/agent-framework/',
      'https://learn.microsoft.com/en-us/agent-framework/agents/tools/local-mcp-tools',
      'https://github.com/microsoft/agent-framework',
      'https://github.com/microsoft/autogen',
      'examples/microsoft-agent-framework-workpaper-mcp/scripts/check-microsoft-agent-framework-recipe.py',
      'MCPStdioTool',
      'MCPStreamableHTTPTool',
      '@bilig/workpaper@latest',
      'set_cell_contents_and_readback',
      'Summary!B3',
      '60000',
      '96000',
      'No upstream Microsoft Agent Framework PR or issue was opened',
    ],
  },
  {
    path: 'docs/trae-workpaper-mcp.md',
    includes: [
      'Trae WorkPaper MCP setup',
      'https://docs.trae.ai/ide/model-context-protocol',
      'https://docs.trae.ai/ide/add-mcp-servers',
      'https://docs.trae.ai/ide/use-mcp-servers-in-agents',
      'https://docs.trae.ai/ide/rules',
      'https://docs.trae.ai/ide/skills',
      '.trae/mcp.json',
      '.trae/rules/bilig-workpaper.md',
      '@bilig/workpaper@latest',
      'Project MCP',
      'set_cell_contents_and_readback',
      'Summary!B3',
      '60000',
      '96000',
      'verified: true',
      'No upstream Trae PR or issue was opened',
    ],
  },
  {
    path: 'docs/qodo-workpaper-mcp.md',
    includes: [
      'Qodo WorkPaper MCP setup',
      'https://docs.qodo.ai/qodo-documentation/qodo-ide/tools-mcps/agentic-tools-mcps',
      'https://docs.qodo.ai/qodo-documentation/qodo-review/configuration/qodo-merge-configuration',
      'Qodo IDE Agentic Tools MCP settings',
      'mcpServers',
      '@bilig/workpaper@latest',
      'bilig-agent-start --rules qodo',
      'set_cell_contents_and_readback',
      'Summary!B3',
      '60000',
      '96000',
      'verified: true',
      'No upstream Qodo PR, issue, or listing was opened',
    ],
  },
  {
    path: 'docs/goose-workpaper-mcp.md',
    includes: [
      'Goose WorkPaper MCP Recipe',
      'https://goose-docs.ai/docs/getting-started/using-extensions/',
      'https://goose-docs.ai/docs/guides/recipes/recipe-reference/',
      'https://goose-docs.ai/docs/guides/goose-cli-commands/',
      'examples/goose-workpaper-mcp/recipe.yaml',
      'goose recipe validate examples/goose-workpaper-mcp/recipe.yaml',
      'goose run --recipe examples/goose-workpaper-mcp/recipe.yaml --debug',
      '@bilig/workpaper@latest',
      'set_cell_contents_and_readback',
      'Summary!B3',
      '60000',
      '96000',
      'verified: true',
      'No upstream Goose PR or issue was opened',
    ],
  },
  {
    path: 'examples/goose-workpaper-mcp/README.md',
    includes: [
      'Goose WorkPaper MCP Recipe',
      'goose recipe validate examples/goose-workpaper-mcp/recipe.yaml',
      'goose run --recipe examples/goose-workpaper-mcp/recipe.yaml --debug',
      '@bilig/workpaper@latest',
      'set_cell_contents_and_readback',
      'Inputs!B3',
      'Summary!B3',
      '60000',
      '96000',
      'No upstream Goose PR or issue was opened',
    ],
  },
  {
    path: 'examples/goose-workpaper-mcp/recipe.yaml',
    includes: [
      'version: "1.0.0"',
      'title: Bilig WorkPaper MCP proof',
      'type: stdio',
      'name: bilig-workpaper',
      'cmd: npm',
      '- bilig-workpaper-mcp',
      '- ./pricing.workpaper.json',
      'set_cell_contents_and_readback',
    ],
  },
  {
    path: 'examples/goose-workpaper-mcp/scripts/check-goose-recipe.py',
    includes: [
      'require_includes(ROOT / "README.md", "Goose WorkPaper MCP Recipe")',
      'require_includes(ROOT / "README.md", "goose recipe validate examples/goose-workpaper-mcp/recipe.yaml")',
      'require_includes(ROOT / "README.md", "set_cell_contents_and_readback")',
      'require_includes(ROOT / "recipe.yaml", "type: stdio")',
      'require_includes(REPO_ROOT / "docs" / "goose-workpaper-mcp.md", "https://goose-docs.ai/docs/guides/recipes/recipe-reference/")',
    ],
  },
  {
    path: 'examples/microsoft-agent-framework-workpaper-mcp/README.md',
    includes: [
      'Microsoft Agent Framework WorkPaper MCP tools',
      'MCPStdioTool',
      'MCPStreamableHTTPTool',
      '@bilig/workpaper@latest',
      'set_cell_contents_and_readback',
      'Inputs!B3',
      'Summary!B3',
      '60000',
      '96000',
      'python examples/microsoft-agent-framework-workpaper-mcp/scripts/check-microsoft-agent-framework-recipe.py',
    ],
  },
  {
    path: 'examples/microsoft-agent-framework-workpaper-mcp/scripts/check-microsoft-agent-framework-recipe.py',
    includes: [
      'require_includes(ROOT / "README.md", "Microsoft Agent Framework WorkPaper MCP tools")',
      'require_includes(ROOT / "README.md", "MCPStdioTool")',
      'require_includes(ROOT / "README.md", "MCPStreamableHTTPTool")',
      'require_includes(ROOT / "README.md", "set_cell_contents_and_readback")',
      'require_includes(REPO_ROOT / "docs" / "microsoft-agent-framework-workpaper-mcp.md", "MCPStdioTool")',
    ],
  },
  {
    path: 'docs/openhands-workpaper-mcp.md',
    includes: [
      'OpenHands WorkPaper MCP setup',
      'https://docs.openhands.dev/openhands/usage/cli/mcp-servers',
      'https://docs.openhands.dev/overview/skills',
      'https://docs.openhands.dev/sdk/arch/skill',
      'openhands mcp add bilig-workpaper --transport stdio npm --',
      '~/.openhands/mcp.json',
      '.agents/skills/bilig-workpaper/SKILL.md',
      '@bilig/workpaper@latest',
      'set_cell_contents_and_readback',
      'npm create @bilig/workpaper@latest . -- --add-agent',
      'No upstream OpenHands PR or issue was opened',
    ],
  },
  {
    path: 'docs/opencode-workpaper-mcp.md',
    includes: [
      'OpenCode WorkPaper MCP setup',
      'https://opencode.ai/docs/config/',
      'https://opencode.ai/docs/mcp-servers/',
      'https://opencode.ai/docs/agents/',
      'opencode.jsonc',
      '.opencode/agents/bilig-workpaper.md',
      '@bilig/workpaper@latest',
      'set_cell_contents_and_readback',
      'npm create @bilig/workpaper@latest . -- --add-agent',
      'No upstream OpenCode PR or issue was opened',
    ],
  },
  {
    path: 'examples/google-adk-workpaper-mcp/README.md',
    includes: [
      'Google ADK WorkPaper MCP tools',
      'uv run --python 3.12 --with google-adk --with mcp',
      'McpToolset',
      'StdioConnectionParams',
      'StdioServerParameters',
      'set_cell_contents_and_readback',
      '60000',
      '96000',
      'python examples/google-adk-workpaper-mcp/scripts/check-google-adk-recipe.py',
    ],
  },
  {
    path: 'examples/google-adk-workpaper-mcp/google_adk_workpaper_mcp.py',
    includes: [
      'from google.adk.tools.mcp_tool import McpToolset',
      'from google.adk.tools.mcp_tool.mcp_session_manager import StdioConnectionParams',
      'from mcp import StdioServerParameters',
      'tool_filter=MCP_TOOL_FILTER',
      '"read_range"',
      '"set_cell_contents_and_readback"',
      '"export_workpaper_document"',
      'restoredReadbackMatchesAfter',
      '"verified": True',
    ],
  },
  {
    path: 'examples/google-adk-workpaper-mcp/scripts/check-google-adk-recipe.py',
    includes: [
      'require_includes(ROOT / "README.md", "uv run --python 3.12 --with google-adk --with mcp")',
      'require_includes(ROOT / "google_adk_workpaper_mcp.py", "McpToolset")',
      'require_includes(ROOT / "google_adk_workpaper_mcp.py", "tool_filter=MCP_TOOL_FILTER")',
      'require_includes(ROOT / "google_adk_workpaper_mcp.py", \'"set_cell_contents_and_readback"\')',
    ],
  },
  {
    path: 'docs/copilotkit-workpaper-spreadsheet-action.md',
    includes: [
      'CopilotKit WorkPaper spreadsheet action',
      '@bilig/workpaper',
      'useCopilotAction',
      'pnpm --dir examples/headless-workpaper run agent:framework-adapters',
    ],
  },
  {
    path: 'docs/cloudflare-agents-workpaper-spreadsheet-tool.md',
    includes: [
      'Cloudflare Agents WorkPaper spreadsheet tool',
      '@bilig/workpaper',
      'agentTool',
      'pnpm --dir examples/headless-workpaper run agent:framework-adapters',
    ],
  },
  {
    path: 'docs/crewai-workpaper-spreadsheet-tool.md',
    includes: [
      'CrewAI WorkPaper spreadsheet tool',
      '@bilig/workpaper',
      'JSON contract',
      'pnpm --dir examples/headless-workpaper run agent:framework-adapters',
    ],
  },
  {
    path: 'docs/browser-use-workpaper-formula-tool.md',
    includes: [
      'Browser Use WorkPaper formula tool',
      'https://docs.browser-use.com/open-source/customize/tools/basics',
      'https://docs.browser-use.com/open-source/customize/tools/add',
      'https://docs.browser-use.com/open-source/customize/tools/response',
      'https://docs.browser-use.com/open-source/customize/agent/all-parameters',
      'https://docs.browser-use.com/open-source/customize/integrations/mcp-server',
      '@bilig/workpaper@latest',
      'npm exec --yes --package @bilig/workpaper@latest -- bilig-evaluate --door agent-mcp --json',
      'Tools()',
      '@tools.action',
      'ActionResult',
      'set_cell_contents_and_readback',
      'https://github.com/browser-use/browser-use/pull/4909',
      'Do not open a second Browser Use PR',
      '60000',
      '96000',
      'verified: true',
    ],
  },
  {
    path: 'docs/semantic-kernel-workpaper-mcp.md',
    includes: [
      'Semantic Kernel WorkPaper MCP Plugin',
      'MCPStdioPlugin',
      'examples/semantic-kernel-workpaper-mcp',
      '@bilig/workpaper@latest',
      'Summary!B3',
      '60000',
      '96000',
      'afterRestartExpectedArr',
      'verified',
    ],
  },
] as const
