import type { createEngineFormulaBindingService } from './services/formula-binding-service.js'
import type { createEngineFormulaGraphService } from './services/formula-graph-service.js'
import type { createEngineMaintenanceService } from './services/maintenance-service.js'
import type { createEngineMutationSupportService } from './services/mutation-support-service.js'
import type { createEngineOperationService } from './services/operation-service.js'
import type { createEnginePivotService } from './services/pivot-service.js'
import type { createEngineRecalcService } from './services/recalc-service.js'
import type { createEngineTraversalService } from './services/traversal-service.js'

export type EngineMutationSupportRuntimeConfig = Omit<
  Parameters<typeof createEngineMutationSupportService>[0],
  | 'removeFormula'
  | 'rebindFormulasForSheet'
  | 'applyDerivedOp'
  | 'scheduleWasmProgramSync'
  | 'collectFormulaDependents'
  | 'ensureRecalcScratchCapacity'
  | 'getChangedInputEpoch'
  | 'setChangedInputEpoch'
  | 'getChangedInputSeen'
  | 'setChangedInputSeen'
  | 'getChangedInputBuffer'
  | 'setChangedInputBuffer'
  | 'getChangedFormulaEpoch'
  | 'setChangedFormulaEpoch'
  | 'getChangedFormulaSeen'
  | 'setChangedFormulaSeen'
  | 'getChangedFormulaBuffer'
  | 'setChangedFormulaBuffer'
  | 'getChangedUnionEpoch'
  | 'setChangedUnionEpoch'
  | 'getChangedUnionSeen'
  | 'setChangedUnionSeen'
  | 'getChangedUnion'
  | 'setChangedUnion'
  | 'getMutationRoots'
  | 'setMutationRoots'
  | 'getMaterializedCellCount'
  | 'setMaterializedCellCount'
  | 'getMaterializedCells'
  | 'setMaterializedCells'
  | 'getExplicitChangedEpoch'
  | 'setExplicitChangedEpoch'
  | 'getExplicitChangedSeen'
  | 'setExplicitChangedSeen'
  | 'getExplicitChangedBuffer'
  | 'setExplicitChangedBuffer'
  | 'getImpactedFormulaEpoch'
  | 'setImpactedFormulaEpoch'
  | 'getImpactedFormulaSeen'
  | 'setImpactedFormulaSeen'
  | 'getImpactedFormulaBuffer'
  | 'setImpactedFormulaBuffer'
>

export type EngineFormulaBindingRuntimeConfig = Omit<
  Parameters<typeof createEngineFormulaBindingService>[0],
  | 'compiledPlans'
  | 'formulaInstances'
  | 'formulaFamilies'
  | 'regionGraph'
  | 'resolveTemplateForCell'
  | 'exactLookup'
  | 'sortedLookup'
  | 'ensureCellTracked'
  | 'ensureCellTrackedByCoords'
  | 'markFormulaChanged'
  | 'forEachSheetCell'
  | 'lookup'
  | 'resolveStructuredReference'
  | 'resolveSpillReference'
  | 'scheduleWasmProgramSync'
>

export type EngineFormulaGraphRuntimeConfig = Omit<
  Parameters<typeof createEngineFormulaGraphService>[0],
  'rebuildCalcChain' | 'notifyCellValueWritten' | 'forEachFormulaDependencyCell' | 'collectFormulaDependents'
>

export type EngineRecalcRuntimeConfig = Omit<
  Parameters<typeof createEngineRecalcService>[0],
  | 'beginMutationCollection'
  | 'markInputChanged'
  | 'markFormulaChanged'
  | 'markExplicitChanged'
  | 'composeMutationRoots'
  | 'composeEventChanges'
  | 'captureChangedCells'
  | 'captureChangedPatches'
  | 'unionChangedSets'
  | 'composeChangedRootsAndOrdered'
  | 'emptyChangedSet'
  | 'ensureRecalcScratchCapacity'
  | 'getPendingKernelSync'
  | 'getDeferredKernelSyncCount'
  | 'setDeferredKernelSyncCount'
  | 'getDeferredKernelSyncEpoch'
  | 'setDeferredKernelSyncEpoch'
  | 'getDeferredKernelSyncSeen'
  | 'getWasmBatch'
  | 'getChangedInputBuffer'
  | 'flushWasmProgramSync'
  | 'dirtyScheduler'
  | 'beginEvaluationBudget'
  | 'endEvaluationBudget'
  | 'checkEvaluationBudget'
  | 'materializeSpill'
  | 'clearOwnedSpill'
  | 'evaluateDirectLookupFormula'
  | 'evaluateUnsupportedFormula'
  | 'materializePivot'
>

export type EngineMaintenanceRuntimeConfig = Omit<
  Parameters<typeof createEngineMaintenanceService>[0],
  | 'captureSheetCellState'
  | 'captureRowRangeCellState'
  | 'captureColumnRangeCellState'
  | 'setMaterializedCellCount'
  | 'resetFormulaRuntimeCaches'
  | 'scheduleWasmProgramSync'
>

export type EnginePivotRuntimeConfig = Omit<
  Parameters<typeof createEnginePivotService>[0],
  | 'ensureCellTrackedByCoords'
  | 'forEachSheetCell'
  | 'flushDeferredKernelSync'
  | 'scheduleWasmProgramSync'
  | 'flushWasmProgramSync'
  | 'applyDerivedOp'
>

export type EngineOperationRuntimeConfig = Omit<
  Parameters<typeof createEngineOperationService>[0],
  | 'getSelectionState'
  | 'setSelection'
  | 'hasRegionFormulaSubscriptionsForColumn'
  | 'hasRegionFormulaSubscriptionsOverlappingRange'
  | 'getRegionFormulaSubscriptionCount'
  | 'collectRegionFormulaDependentsForCell'
  | 'collectSingleRegionFormulaDependentForCell'
  | 'prepareRegionQueryIndices'
  | 'rewriteDefinedNamesForSheetRename'
  | 'rewriteCellFormulasForSheetRename'
  | 'estimatePotentialNewCells'
  | 'rebindDefinedNameDependents'
  | 'collectFormulaCellsForDefinedNames'
  | 'rebindTableDependents'
  | 'rebindFormulaCells'
  | 'rebindFormulasForSheet'
  | 'removeSheetRuntime'
  | 'applyStructuralAxisOp'
  | 'clearOwnedSpill'
  | 'clearPivotForCell'
  | 'clearOwnedPivot'
  | 'removeFormula'
  | 'bindFormula'
  | 'setInvalidFormulaValue'
  | 'beginEvaluationBudget'
  | 'endEvaluationBudget'
  | 'checkEvaluationBudget'
  | 'beginMutationCollection'
  | 'markInputChanged'
  | 'markFormulaChanged'
  | 'markVolatileFormulasChanged'
  | 'markSpillRootsChanged'
  | 'markPivotRootsChanged'
  | 'markExplicitChanged'
  | 'composeMutationRoots'
  | 'composeEventChanges'
  | 'composeDisjointEventChanges'
  | 'captureChangedCells'
  | 'captureChangedPatches'
  | 'getChangedInputBuffer'
  | 'ensureRecalcScratchCapacity'
  | 'ensureCellTracked'
  | 'resetMaterializedCellScratch'
  | 'syncDynamicRanges'
  | 'rebuildTopoRanks'
  | 'detectCycles'
  | 'recalculate'
  | 'evaluateDirectFormula'
  | 'evaluateFormulaCell'
  | 'reconcilePivotOutputs'
>

export type EngineTraversalRuntimeConfig = Omit<Parameters<typeof createEngineTraversalService>[0], 'regionGraph'>
